services:
  pg_db:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./api/.env
  recipe-book-api:
    build:
      context: ./api
    ports:
      - "3080:3080"
    links:
      - pg_db
    container_name: recipe-book-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
    env_file:
       - ./api/.env
  recipe-book-ui:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    container_name: recipe-book-ui
    stdin_open: true
    volumes:
       - ./ui:/usr/src/app/ui
       - /usr/src/app/ui/node_modules
volumes:
  progresDB:
######## Other containers #########